name: mcp_flutter_chat
description: A Flutter chat app with MCP integration for web, Android, and iOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # HTTP and WebSocket
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # State Management
  provider: ^6.1.1
  
  # JSON and Data
  json_annotation: ^4.8.1
  
  # UUID generation
  uuid: ^4.2.1
  
  # URL launcher for web
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/

flutter_web:
  canvaskit: auto
